project_id = "vdsryddwzhcnoksamkep"

[functions.monday-sync]
verify_jwt = true

[functions.model-save]
verify_jwt = true

[functions.model-get]
verify_jwt = true

[functions.query-aggregate]
verify_jwt = true

[functions.sheet-fetch]
verify_jwt = true

[functions.drive-import]
verify_jwt = true

[functions.dataset-index]
verify_jwt = true

[functions.insights-generate]
verify_jwt = true

[functions.nl-query]
verify_jwt = true

[functions.model-auto]
verify_jwt = true

[functions.dashboard]
verify_jwt = true

[functions.alerts-run]
verify_jwt = true

[functions.executive-snapshot]
verify_jwt = true
