project_id = "vdsryddwzhcnoksamkep"

[functions.monday-sync]
verify_jwt = true

[functions.model-save]
verify_jwt = true

[functions.model-get]
verify_jwt = true

[functions.query-aggregate]
verify_jwt = true

[functions.sheet-fetch]
verify_jwt = false
